### ISSUE TITLE
Update needed ahead of Matrix 1.6-2 release

### ISSUE THREAD

**Issue by jaganmn** [cysouw/qlcMatrix#2]
I sent two e-mails to `maintainer("qlcMatrix")`, on Sep 16 and Oct 7, but did not receive a response.  Is GitHub preferred?  The gist is that **qlcMatrix** fails its checks under forthcoming version 1.6-2 of **Matrix**.  **Matrix** 1.6-2 is due to be released in November, so a patched version of **qlcMatrix** should be submitted to CRAN "soon" to avoid unnecessary archival.  The relevant part of the first e-mail is pasted below.

> your package code has relied on a now-fixed bug in **Matrix**, whereby the _numeric_ product of two _boolean_ matrices returned a boolean rather than numeric matrix.  That is, **qlcMatrix** has used
>
>     <nMatrix> %*% <nMatrix> = <nMatrix>
>
> but the behaviour is now (as always intended)
>    
>     <nMatrix> %*% <nMatrix> = <dMatrix>
>
> If you need a boolean result, then use the boolean product operator, which is `%&%`, _not_ `%*%`.  And if you need a numeric result, use `%*%`, not `%&%`.
>
> I did investigate a bit, and it seems that the functions that you define in `R/split.R` are the immediate reason for the check failure under **Matrix** 1.6-2.
>
> Please revise your package and test that it passes its checks under the latest **Matrix**-devel, which you can install with
>
>     install.packages("Matrix", repos = "http://R-Forge.R-project.org")

IIRC only minimal changes are required.  Do let me know if you are unsure how to adjust your code.  Then I can revisit the code and try to provide a patch.

**Comment by jaganmn** [comment]
We will be submitting Matrix 1.6-2 as early as Nov 3, at which point you may receive a notice from CRAN.

**Comment by cysouw** [comment]
Sorry for the delay: I have tried to fix all problems and I am about to upload a new version to CRAN. Can you please try devtools::install_github("cysouw/qlcMatrix") to check if everything is working on your side?

**Comment by jaganmn** [comment]
I did:

```sh
$ git clone git@github.com:cysouw/qlcMatrix.git
$ R CMD build --compact-vignettes=gs+qpdf qlcMatrix
$ R CMD check --as-cran qlcMatrix_0.9.8.tar.gz
```

And found:

```
* checking for hidden files and directories ... NOTE
Found the following hidden files and directories:
  .github
These were most likely included in error. See section 'Package
structure' in the 'Writing R Extensions' manual.

CRAN-pack does not know about
  .github
```

Otherwise the check was OK under Matrix 1.7.  Maybe just add `^[.]github$` to `.Rbuildignore` ... ?

**Comment by cysouw** [comment]
check! thx.
