### ISSUE TITLE
Not availabel on R 4.3.2

### ISSUE THREAD

**Issue by jowodo** [cysouw/qlcMatrix#3]
Hi, 

I want to install [hdWGCNA](https://github.com/smorabit/hdWGCNA) which depends on qlcMatrix, but when I try to install from CRAN, I get this error message: 
INPUT (from `bash`): 
```
echo 'install.packages("qlcMatrix")' | R --no-save
```
OUTPUT: 
```
R version 4.3.2 (2023-10-31) -- "Eye Holes"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages("qlcMatrix")
Warning message:
package 'qlcMatrix' is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
>
```
installing from github works. (from within `R`)
```
install.packages("devtools")
devtools::install_github("cysouw/qlcMatrix")
```

**Comment by pettyalex** [comment]
qlcMatrix was removed from CRAN because it failed a test: https://cran.r-project.org/web/packages/qlcMatrix/index.html

It would have to be fixed and re-uploaded by the maintainer to become available on CRAN again.

**Comment by jowodo** [comment]
Unfortunately the [last update](https://cran.r-project.org/src/contrib/Archive/qlcMatrix/) on cran was on 2018-04-20
It seems that this project is dead ...

**Comment by cysouw** [comment]
no, it's not dead! However, I'm working on other things, so this went under the radar, sorry.

I have tried to fix all problems and I am about to upload a new version to CRAN. Can you please try devtools::install_github("cysouw/qlcMatrix") to check if everything is working on your side?

**Comment by jowodo** [comment]
thanks for the response and the fixing, but I don't work at the same premise. If it can be installed to R 4.3, this issue can be closed.

**Comment by cysouw** [comment]
qlcMatrix should be back on CRAN any moment now!
