### ISSUE TITLE
qlcMatrix has been removed from CRAN, it would be great if it were restored

### ISSUE THREAD

**Issue by pettyalex** [cysouw/qlcMatrix#4]
qlcMatrix was removed from CRAN on 2023/11/29 because of what looks like a very minor problem with the examples: https://cran.r-project.org/web/packages/qlcMatrix/index.html

This disrupted any packages that depended on qlcMatrix, and it'd be great if qlcMatrix could be fixed so that it can be distributed on CRAN again.

**Comment by aubreyodom** [comment]
Seconding this, thanks!

**Comment by cysouw** [comment]
Sorry for the delay: I have tried to fix all problems and I am about to upload a new version to CRAN. Can you please try `devtools::install_github("cysouw/qlcMatrix")` to check if everything is working on your side?

**Comment by cysouw** [comment]
Should be back on CRAN any moment now!
